### ISSUE TITLE
Suggestion: Add audio with pronunciation of countries

### ISSUE THREAD

**Issue by Jam-u** [anki-geo/ultimate-geography#492] opened 2021-11-26 21:33 UTC
Learning the names of countries without the pronunciation quickly turns into mindless repetition for me where things don't go in efficiently. When I know how a country/capital is pronounced, it is much easy to learn. It would also help so people don't mispronounce capitals/countries

Maybe there can be two fields added -- Country Pronunciation and Capital Pronunciation?

**Comment by ukanuk** [comment] 2021-11-27 03:19
This is a duplicate of issue #81, where there has already been significant discussion. For myself, I've modified the card templates to add a dynamic link to the forvo.com pronunciations. See issue #81 for more details.

**Comment by aplaice** [comment] 2021-11-27 10:18
Thanks for the suggestion! As @ukanuk wrote, it's a duplicate of #81, though, so I'm closing this issue.

Please comment at #81 if you have any further suggestions.

**Closed by aplaice** 2021-11-27 10:18 UTC
